// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/main/resources/m3u.lex

package es.m3u_parser.lexer;

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
public final class M3uLexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int EXTM3U = 2;
  public static final int EXTINF = 4;
  public static final int TVGNAME = 6;
  public static final int TVGID = 8;
  public static final int TVGLOGO = 10;
  public static final int GROUP_TITLE = 12;
  public static final int GROUP_TITLE_SPANISH = 14;
  public static final int NAME = 16;
  public static final int URL = 18;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7, 
     8,  8,  9, 9
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0300\10\u0400\u1020\u0300";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\0\1\3\22\0\1\4\1\5"+
    "\1\6\1\7\10\5\1\10\1\11\1\5\1\12\1\13"+
    "\1\14\1\5\1\15\6\5\1\16\2\5\1\17\6\5"+
    "\1\20\1\21\1\22\2\5\1\23\2\5\1\24\1\25"+
    "\1\26\1\5\1\27\2\5\1\30\1\31\1\32\1\33"+
    "\1\5\1\34\10\5\1\35\3\5\1\36\1\5\1\37"+
    "\1\40\1\41\2\5\1\42\1\43\1\44\1\45\1\46"+
    "\1\5\1\47\1\50\1\51\1\52\1\53\u019d\5\u02ec\0";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1280];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\10\0\1\1\1\0\1\2\2\3\1\2\1\3\3\2"+
    "\2\4\1\5\1\2\1\1\1\6\2\2\1\7\1\2"+
    "\1\10\1\1\1\11\3\1\2\12\1\2\5\0\1\13"+
    "\3\0\1\14\2\0\2\1\10\0\1\15\1\1\10\0"+
    "\1\1\10\0\1\16\16\0\1\17\1\0\1\20\4\0"+
    "\1\21\6\0\1\22\1\23\10\0\1\24\2\0\1\25"+
    "\4\0\1\26";

  private static int [] zzUnpackAction() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\130\0\204\0\260\0\334\0\u0108\0\u0134"+
    "\0\u0160\0\u018c\0\u01b8\0\u01b8\0\u01e4\0\u0210\0\u023c\0\u0268"+
    "\0\u0294\0\u02c0\0\u01b8\0\u02ec\0\u0318\0\u0344\0\u01b8\0\u0370"+
    "\0\u039c\0\u03c8\0\u03f4\0\u0420\0\u01b8\0\u044c\0\u01b8\0\u0478"+
    "\0\u04a4\0\u04d0\0\u01b8\0\u04fc\0\u0528\0\u0554\0\u0580\0\u05ac"+
    "\0\u05d8\0\u039c\0\u01b8\0\u0604\0\u03c8\0\u0630\0\u01b8\0\u065c"+
    "\0\u0688\0\u06b4\0\u06e0\0\u070c\0\u0738\0\u0764\0\u0790\0\u07bc"+
    "\0\u07e8\0\u0814\0\u0840\0\u044c\0\u086c\0\u0898\0\u08c4\0\u08f0"+
    "\0\u091c\0\u0948\0\u0974\0\u09a0\0\u09cc\0\u09f8\0\u0a24\0\u0a50"+
    "\0\u0a7c\0\u0aa8\0\u0ad4\0\u0b00\0\u0b2c\0\u0b58\0\u01b8\0\u0b84"+
    "\0\u0bb0\0\u0bdc\0\u0c08\0\u0c34\0\u0c60\0\u0c8c\0\u0cb8\0\u0ce4"+
    "\0\u0d10\0\u0d3c\0\u0d68\0\u0d94\0\u0dc0\0\u01b8\0\u0dec\0\u01b8"+
    "\0\u0e18\0\u0e44\0\u0e70\0\u0e9c\0\u01b8\0\u0ec8\0\u0ef4\0\u0f20"+
    "\0\u0f4c\0\u0f78\0\u0fa4\0\u01b8\0\u01b8\0\u0fd0\0\u0ffc\0\u1028"+
    "\0\u1054\0\u1080\0\u10ac\0\u10d8\0\u1104\0\u01b8\0\u1130\0\u115c"+
    "\0\u01b8\0\u1188\0\u11b4\0\u11e0\0\u120c\0\u01b8";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\2\13\1\14\1\15\3\13\1\16\1\17\26\13\1\20"+
    "\1\21\10\13\1\22\4\13\1\23\1\24\51\13\1\25"+
    "\1\13\2\25\4\13\1\26\1\13\1\27\41\13\1\30"+
    "\1\13\2\30\1\13\1\31\46\13\1\25\1\13\2\25"+
    "\1\13\1\32\46\13\1\33\1\13\2\33\1\13\1\32"+
    "\53\13\1\34\55\13\1\35\44\13\1\36\1\37\1\40"+
    "\2\36\1\13\12\36\1\41\11\36\1\42\20\36\2\13"+
    "\1\43\1\44\34\13\1\45\13\13\56\0\1\14\72\0"+
    "\1\46\33\0\1\17\1\0\3\17\1\0\45\17\47\0"+
    "\1\47\55\0\1\50\55\0\1\51\2\0\1\23\52\0"+
    "\1\25\1\0\2\25\63\0\1\27\40\0\1\30\1\0"+
    "\2\30\50\0\1\52\1\0\3\52\1\53\12\52\1\54"+
    "\32\52\1\0\1\55\1\0\3\55\1\27\45\55\1\0"+
    "\1\33\1\0\2\33\50\0\1\56\1\0\3\56\1\57"+
    "\15\56\1\60\1\61\26\56\1\0\1\36\1\0\3\36"+
    "\1\0\45\36\1\0\1\36\1\37\3\36\1\0\45\36"+
    "\1\0\1\36\1\0\3\36\1\0\21\36\1\62\23\36"+
    "\1\0\1\36\1\0\3\36\1\0\14\36\1\63\30\36"+
    "\2\0\1\43\122\0\1\64\36\0\1\65\64\0\1\66"+
    "\57\0\1\67\41\0\1\70\15\0\1\52\1\0\3\52"+
    "\1\53\12\52\1\54\6\52\1\71\23\52\1\0\1\56"+
    "\1\0\3\56\1\57\45\56\1\0\1\56\1\0\3\56"+
    "\1\57\32\56\1\72\12\56\1\0\1\56\1\0\3\56"+
    "\1\57\36\56\1\73\6\56\1\0\1\36\1\0\3\36"+
    "\1\0\7\36\1\74\35\36\1\0\1\36\1\0\3\36"+
    "\1\0\20\36\1\75\24\36\51\0\1\76\33\0\1\77"+
    "\74\0\1\100\47\0\1\101\16\0\1\102\43\0\1\52"+
    "\1\0\3\52\1\53\7\52\1\103\2\52\1\54\32\52"+
    "\1\0\1\56\1\0\3\56\1\57\44\56\1\104\1\0"+
    "\1\56\1\0\3\56\1\57\44\56\1\105\1\0\1\36"+
    "\1\0\1\36\1\106\1\36\1\0\45\36\46\0\1\107"+
    "\30\0\1\110\1\0\1\111\74\0\1\112\23\0\1\113"+
    "\60\0\1\114\16\0\1\115\1\0\1\116\10\0\1\103"+
    "\1\0\3\103\1\117\45\103\1\0\1\56\1\0\3\56"+
    "\1\57\27\56\1\120\15\56\1\0\1\56\1\0\3\56"+
    "\1\57\32\56\1\121\12\56\1\0\1\36\1\0\3\36"+
    "\1\0\12\36\1\41\32\36\16\0\1\122\63\0\1\123"+
    "\42\0\1\124\47\0\1\125\54\0\1\126\61\0\1\127"+
    "\100\0\1\130\43\0\1\131\17\0\1\56\1\0\3\56"+
    "\1\57\7\56\1\132\35\56\1\0\1\56\1\0\3\56"+
    "\1\57\27\56\1\133\15\56\12\0\1\134\63\0\1\135"+
    "\63\0\1\136\72\0\1\137\14\0\1\17\60\0\1\140"+
    "\73\0\1\141\57\0\1\142\11\0\1\56\1\0\1\56"+
    "\1\143\1\56\1\57\45\56\1\0\1\56\1\0\3\56"+
    "\1\57\41\56\1\144\3\56\12\0\1\36\57\0\1\145"+
    "\76\0\1\146\57\0\1\147\44\0\1\150\16\0\1\56"+
    "\1\0\3\56\1\57\21\56\1\151\23\56\1\0\1\56"+
    "\1\0\3\56\1\57\7\56\1\152\35\56\51\0\1\153"+
    "\21\0\1\154\53\0\1\155\35\0\1\56\1\0\3\56"+
    "\1\57\37\56\1\156\5\56\1\0\1\56\1\0\1\56"+
    "\1\157\1\56\1\57\45\56\42\0\1\160\12\0\1\56"+
    "\1\0\3\56\1\57\26\56\1\161\16\56\1\0\1\56"+
    "\1\0\3\56\1\57\21\56\1\162\23\56\36\0\1\163"+
    "\16\0\1\56\1\0\3\56\1\57\32\56\1\164\12\56"+
    "\1\0\1\56\1\0\3\56\1\57\37\56\1\165\5\56"+
    "\17\0\1\166\35\0\1\56\1\0\3\56\1\57\35\56"+
    "\1\167\7\56\1\0\1\56\1\0\3\56\1\57\26\56"+
    "\1\170\16\56\1\0\1\56\1\0\3\56\1\171\45\56"+
    "\1\0\1\56\1\0\3\56\1\57\35\56\1\172\7\56"+
    "\1\0\1\56\1\0\3\56\1\57\32\56\1\173\12\56"+
    "\1\0\1\56\1\0\3\56\1\57\41\56\1\174\3\56"+
    "\1\0\1\56\1\0\3\56\1\57\31\56\1\175\13\56"+
    "\1\0\1\56\1\0\3\56\1\176\45\56";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4664];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\10\0\1\1\1\0\2\11\6\1\1\11\3\1\1\11"+
    "\5\1\1\11\1\1\1\11\3\1\1\11\2\1\5\0"+
    "\1\11\3\0\1\11\2\0\2\1\10\0\2\1\10\0"+
    "\1\1\10\0\1\11\16\0\1\11\1\0\1\11\4\0"+
    "\1\11\6\0\2\11\10\0\1\11\2\0\1\11\4\0"+
    "\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[126];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    /**
     * Create an empty lexer, yyrset will be called later to reset and assign
     * the reader
     */


    StringBuffer sb = new StringBuffer();
    boolean spanishChannel = false;
    boolean spanishMovies = false;
    boolean onError = false;
    public M3uLexer() {
        super();
    }

    public void append(String text) {
        if (!onError) {
            sb.append(text);
        }
    }

    public void print() {
        if (!onError) {
           System.out.print(sb.toString());
        }
        reset();
    }

    public void reset() {
        sb = new StringBuffer();
        onError = false;
        spanishChannel = false;
        spanishMovies = false;
    }

    public void setError(String text) {
        onError = true;
        //System.out.println("ERROR: " + text);
        //System.out.println("spanishChannel=" + spanishChannel);
        //System.out.println("spanishMovies=" + spanishMovies);

    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public M3uLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
          {         print();
        return 0;
 }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { append(yytext());
            }
            // fall through
          case 23: break;
          case 2:
            { System.out.print(yytext());
            }
            // fall through
          case 24: break;
          case 3:
            { /* ignore */
            }
            // fall through
          case 25: break;
          case 4:
            { append(yytext());  print(); yybegin(YYINITIAL);
            }
            // fall through
          case 26: break;
          case 5:
            { append(yytext()); yybegin(YYINITIAL);
            }
            // fall through
          case 27: break;
          case 6:
            { append(yytext());
                   yybegin(YYINITIAL);
            }
            // fall through
          case 28: break;
          case 7:
            { append(yytext());
                  yybegin(YYINITIAL);
            }
            // fall through
          case 29: break;
          case 8:
            { append(yytext());
                  yybegin(NAME);
            }
            // fall through
          case 30: break;
          case 9:
            { append(yytext());
                   yybegin(URL);
            }
            // fall through
          case 31: break;
          case 10:
            { append(yytext());
                  print();
                  yybegin(YYINITIAL);
            }
            // fall through
          case 32: break;
          case 11:
            { spanishChannel = false;
                   append(yytext());
            }
            // fall through
          case 33: break;
          case 12:
            { setError("group-title" + yytext());
                  yybegin(YYINITIAL);
            }
            // fall through
          case 34: break;
          case 13:
            { /* remove */
            }
            // fall through
          case 35: break;
          case 14:
            { spanishChannel = true;
                   append(yytext());
            }
            // fall through
          case 36: break;
          case 15:
            { append(yytext()); yybegin(EXTM3U);
            }
            // fall through
          case 37: break;
          case 16:
            { append(yytext()); yybegin(TVGID);
            }
            // fall through
          case 38: break;
          case 17:
            { append(yytext()); yybegin(EXTINF);
            }
            // fall through
          case 39: break;
          case 18:
            { append(yytext()); yybegin(TVGLOGO);
            }
            // fall through
          case 40: break;
          case 19:
            { append(yytext()); yybegin(TVGNAME);
            }
            // fall through
          case 41: break;
          case 20:
            { append(yytext()); yybegin(GROUP_TITLE);
            }
            // fall through
          case 42: break;
          case 21:
            { spanishChannel = true;
                   append(yytext());
                   yybegin(GROUP_TITLE_SPANISH);
            }
            // fall through
          case 43: break;
          case 22:
            { spanishMovies = true;
                   append(yytext());
                   yybegin(GROUP_TITLE_SPANISH);
            }
            // fall through
          case 44: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java M3uLexer [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        M3uLexer scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new M3uLexer(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
